# Generated by Django 5.2.7 on 2025-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
