# Generated by Django 5.2.7 on 2026-01-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_notemodel_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='note_type',
            field=models.CharField(choices=[('success', 'Sarning'), ('warning', 'Warning'), ('normal', 'Normal')], default='normal', max_length=25),
        ),
    ]
