# Generated by Django 5.2.7 on 2026-01-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_notemodel_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='note_type',
            field=models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('normal', 'Normal')], default='normal', max_length=25),
        ),
    ]
