# Generated by Django 5.2.7 on 2025-12-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencesmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
