# Generated by Django 5.2.7 on 2025-12-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_licencesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
