# Generated by Django 5.2.7 on 2025-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
