# Generated by Django 5.2.7 on 2025-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobmodel_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencesmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
