# Generated by Django 5.2.7 on 2025-12-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_licencesmodel_updated_at_jobmodel_job_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_redus',
            field=models.FloatField(default=10),
        ),
    ]
