# Generated by Django 5.2.7 on 2025-12-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_address_alter_customuser_user_redus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fund_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fund_usi',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sup_member_no',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_file_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
