# Generated by Django 5.2.7 on 2025-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_date_of_birth_customuser_fund_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='expire_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
