# Generated by Django 6.0 on 2026-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bankcardinfo_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementmodel',
            name='operative_trackers',
            field=models.CharField(choices=[('notstartyet', 'Not Start Yet'), ('on_duty', 'On Duty'), ('shift_completed', 'Shift Completed')], default='notstartyet', max_length=100),
        ),
    ]
