# Generated by Django 5.2.7 on 2026-01-08 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='OperativeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operative_notes', to='api.companymodel')),
                ('operative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_from_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
