# Generated by Django 5.2.7 on 2025-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_percentage_guard', models.BooleanField(default=False)),
                ('is_percentage_company', models.BooleanField(default=False)),
                ('percentage_company', models.IntegerField()),
                ('percentage_guard', models.IntegerField()),
                ('min_referral_user_of_company', models.IntegerField()),
                ('min_referral_user_of_guard', models.IntegerField()),
                ('total_free_days_company', models.IntegerField()),
                ('total_free_days_guard', models.IntegerField()),
            ],
        ),
    ]
